export const ActionTypes = {
    GET_CONTACTS : "GET_CONTACTS",
    SELECT_CONTACT : "SELECT_CONTACT",
    REMOVE_SELECTED_CONTACT : "REMOVE_SELECTED_CONTACT",
    UPDATE_SELECTED_CONTACT : "UPDATE_SELECTED_CONTACT",
    CREATE_CONTACT : "CREATE_CONTACT",
    DELETE_CONTACT : "DELETE_CONTACT",
}